// src/lib/blocks/Blocks.svelte
<script lang="ts">
	import type { Block } from './types';
	import blockMap from './block-map';
	export let blocks: Array<object>;

	let children;
	$: {
		function blockChildren() {
			// loop through blocks and match template to components
			return blocks.map(({ template, ...props }: Block) => {
				return {
					Component: blockMap[template],
					props
				};
			});
		}
		// loop through blocks and match template to components
		children = blockChildren();
	}
</script>

{#each children as { Component, props }}
	<section>
		<Component {...props} />
	</section>
{/each}

// site/.vuepress/components/blocks/Blocks.vue
<template>
  <section>
    <component
      v-for="block in blockChildren"
      :is="block.component"
      v-bind="block.defs"
    />
  </section>
</template>

<script>
import blockMap from "./block-map";

export default {
  props: {
    blocks: {
      type: Array,
      required: true,
    },
  },
  computed: {
    blockChildren: (v) => {
      // loop through blocks and match template to components
      return v.blocks.map(({ template, ...defs }) => {
        return {
          component: template,
          defs,
        };
      });
    },
  },
  components: blockMap,
};
</script>
